baseURL = "http://github.mklau.io"
title = "MKLau"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Data driven ecologist"
title404 = "Doh!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Adapted from MunifTanjim/Minimo"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006Jan02"
listDateFormat = "2006Jan02"
archiveDateFormat = "Jan02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#000000"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about", "social_menu", "taxonomy_cloud"] # 
footer = []

# [params.opengraph.facebook]
# admins = [] # array of Facebook IDs
# appID = ""
# pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "mk@mklau.info"
github = "MKLau"
linkedin = "matthew-lau-47880944"
twitter = "_MKLau_"
google_scholar = "VTZ0MSAAAAAJ"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

# [params.comments.staticman.github]
# username = "MunifTanjim"
# repository = "minimo"
# branch = "master"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"


[[menu.main]]
name = "CV"
weight = -10
identifier = "CV"
url = "https://github.com/mklau/cv_mklau"


# [blackfriday]
# hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
